spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.0.170:3306/sx-shoppingmall?&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
#    username: root
#    password: SXDB!2019@
#    url: jdbc:mysql://172.26.143.103:3306/shoppingmall?&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
#    username: sxtest
#    password: SXV2Test!2020@
    url: jdbc:mysql://127.0.0.1:3306/shoppingmall?&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss    #或java.text.SimpleDateFormat
    time-zone: GMT+8
  devtools:
    restart:
      additional-paths: classpath:src/main/java
  servlet:
    multipart:
      max-file-size: 4MB
server:
  port: 2222
  servlet:
    session:
      timeout: 3600s



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.shopping.**.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config: classpath:logback.xml
  level:
    mapper: debug

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

variables:
#  img_url: /app/resource/shopping/img/
  img_url: D://img/
